apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-depl
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: kube.shothik.com.bd
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-service
            port:
             number: 80
      # - pathType: Prefix
      #   path: "/<path>"
      #   backend:
      #     service:
      #       name: <servcieName>
      #       port:
      #         number: <servicePort>